=== LuoYuanzhen/xml-solver/files/university.dtd
<!ELEMENT university (college+, building+)>
<!ELEMENT college (profession+)>
<!ELEMENT building (room*)>
<!ELEMENT profession (faculty+, student*)>
<!ELEMENT room EMPTY>
<!ELEMENT faculty (professor*, lecturer*)>
<!ELEMENT student EMPTY>
<!ELEMENT professor EMPTY>
<!ELEMENT lecturer EMPTY>
<!ATTLIST university
        name ID #REQUIRED
        location CDATA #REQUIRED
>
<!ATTLIST college
        name ID #REQUIRED
        dean IDREF #REQUIRED
        createData CDATA #IMPLIED
>
<!ATTLIST building
        name ID #REQUIRED
        floor CDATA #IMPLIED
>
<!ATTLIST profession
        name ID #REQUIRED
        departmentHead IDREF #REQUIRED
        rating CDATA #IMPLIED
>
<!ATTLIST room
        id CDATA #REQUIRED
>
<!ATTLIST student
        name ID #REQUIRED
        sex CDATA #REQUIRED
        phone CDATA #IMPLIED
>
<!ATTLIST professor
        name ID #REQUIRED
        sex CDATA #REQUIRED
        room CDATA #IMPLIED
        phone CDATA #IMPLIED
>
<!ATTLIST lecturer
        name ID #REQUIRED
        sex CDATA #REQUIRED
        phone CDATA #IMPLIED
>

=== LuoYuanzhen/xml-solver/files/test_university.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE university SYSTEM "src/main/resources/university.dtd">

<university name="China_University_of_Petromleum" location="Beijing">
    <college name="CISE" dean="WeifengLiu">
        <profession name="CS" departmentHead="LianenJi" rating="B-">
            <faculty>
                <professor name="WeifengLiu" sex="male" phone="188xxxxxxxx"></professor>
                <professor name="LianenJi" sex="male"></professor>
                <lecturer name="JiangboFan" sex="female"></lecturer>
            </faculty>
            <student name="YuanzhenLuo" sex="male" phone="138xxxx7813"/>
        </profession>
    </college>
    <building name="library">
        <room id="303"></room>
    </building>
</university>
